### ISSUE TITLE
Other's Profile Page

### ISSUE THREAD

**Issue by karanBRAVO** [karanBRAVO/KY_VidX#3]
# Profile Page (`OTHERS`)

Complete the other's profile design.

currently, shows the user's id only.

**Comment by alvarotorrestx** [comment]
Hey do you need help with this project? I'd like to help. 😊

**Comment by karanBRAVO** [comment]
Not in this issue, but I want to add the feature of **Downloading the video** along with check pointing. On that part, you can help me out. **Tell me if you can do**, then I will create the issue and assign it to you.
